public enum ErrorCode
{
    NO_ERROR,
    UNKNOWN,
    INVALID_URL,
    INVALID_EMAIL_PASSWORD,
    INVALID_LOGIN_TOKEN,
    USER_ALREADY_REGISTERED,
    ITEM_ALREADY_EXISTS,
    INVALID_MEAL_ENTRY,
    NO_DOCTORS_REGISTERED,
    USER_ALREADY_LOGGED_IN
}
